import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

export type OcrProduct = { product_code: string; norm_per_hour: number | null; confidence: number };
export type OcrRow = { employee_name: string; position: "HA" | "TUP" | null; oee: number | null; performance: number | null; available_time: number | null; confidence: number };
export type OcrHourlyMetric = { hour: number | null; product_code: string | null; actual_output: number | null; performance_pct: number | null; availability_pct: number | null; norm_per_hour: number | null; oee: number | null };
export type OcrStage = "products" | "employees" | "hourly";
export type OcrContext = { product_code: string | null; norm_per_hour: number | null; capacity: number | null; employee_count: number };
export type OcrResult = { work_date: string | null; shift: string | null; line: string | null; product_code: string | null; norm_per_hour: number | null; products: OcrProduct[]; header_confidence: number; rows: OcrRow[]; hourly_metrics: OcrHourlyMetric[]; predicted_shift_output: number | null; productive_minutes: number | null; raw?: string };

const SHIFT_MINUTES = 8 * 60;
const START_PREP_MINUTES = 10;
const BREAK_MINUTES = 30;
const END_CLEANUP_MINUTES = 5;

const SYSTEM = `Jsi OCR/extrakční nástroj pro výrobní screenshoty z výroby DPS. Musíš přečíst celý screenshot. Vrať pouze JSON. Priorita jsou skutečně viditelné řádky pracovníků a hodinová výrobní tabulka. Procenta vracej jako čísla bez %. Desetinnou čárku převáděj na tečku. Nevymýšlej hodnoty. Datum YYYY-MM-DD, směna Ranní/Odpolední/Noční.
PRACOVNÍCI: pro KAŽDÉHO viditelného pracovníka vrať jeden rows objekt. Jméno přesně včetně diakritiky. Pokud je jméno čitelné, pracovníka vrať i když metrika není čitelná; nečitelná metrika=null. OEE, Výkon a Dostupnost ber z jeho řádku. Pokud pozice není čitelná, T_=>TUP a H_=>HA. Product ID nesmí filtrovat pracovníky.
PRODUKTY: přečti hlavní Product ID i všechny produkty z hodinové tabulky a jejich normu ks/h. Norma při 100% dostupnosti je přímý zdroj; jinak ji lze přepočítat na 100%.
HODINY: přečti všechny skutečně viditelné hodiny, product_code, actual_output ze sloupce reálný, performance_pct a availability_pct.\nSchéma: {work_date,shift,line,product_code,norm_per_hour,products:[{product_code,norm_per_hour,confidence}],header_confidence,rows:[{employee_name,position,oee,performance,available_time,confidence}],hourly_metrics:[{hour,product_code,actual_output,performance_pct,availability_pct,norm_per_hour}]} `;
const WORKER_RETRY = `Samostatný druhý průchod stejného screenshotu. Ignoruj hlavičku a soustřeď se pouze na TABULKU PRACOVNÍKŮ. Vrať KAŽDÝ viditelný řádek: employee_name, position, oee, performance, available_time, confidence. Jméno musí být vráceno i při chybějící metrice; nečitelná metrika=null. Neber čísla z hodinové tabulky. Product ID je pouze kontext a nesmí ovlivnit výsledek. Vrať pouze JSON.`;

function toNum(v: unknown): number | null { if (v === null || v === undefined || v === "") return null; if (typeof v === "number") return Number.isFinite(v) ? v : null; let s = String(v).trim().replace(/\s/g, "").replace(/%/g, ""); if (s.includes(",")) s = s.replace(/\./g, "").replace(",", "."); else s = s.replace(/[^\d.\-]/g, ""); const n = Number(s); return Number.isFinite(n) ? n : null; }
function text(v: unknown): string { return String(v ?? "").trim(); }
function firstNum(o: Record<string, unknown>, keys: readonly string[]): number | null { for (const k of keys) { const n = toNum(o[k]); if (n !== null) return n; } return null; }
function firstText(o: Record<string, unknown>, keys: readonly string[]): string { for (const k of keys) { const s = text(o[k]); if (s) return s; } return ""; }
function rawRowsFrom(p: Record<string, unknown>): Record<string, unknown>[] { for (const k of ["rows","employees","workers","employee_rows","employeeRows","worker_rows"]) if (Array.isArray(p[k])) return p[k] as Record<string, unknown>[]; return []; }
function workerName(r: Record<string, unknown>): string { return firstText(r,["employee_name","name","employee","worker_name","worker","jmeno","jméno","zamestnanec","zaměstnanec","pracovnik","pracovník"]); }
function workerScore(p: Record<string, unknown>): number { return rawRowsFrom(p).reduce((s,r)=>s+(workerName(r)?10+["oee","performance","available_time"].reduce((n,k)=>n+(firstNum(r,[k])!==null?2:0),0):0),0); }
function normWorkerKey(v: string): string { return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim(); }
function mergeWorkerRows(...groups: Record<string, unknown>[][]): Record<string, unknown>[] { const out: Record<string, unknown>[]=[]; const by=new Map<string,Record<string,unknown>>(); for(const group of groups) for(const row of group){ const name=workerName(row); if(!name) continue; const key=normWorkerKey(name); const old=by.get(key); if(!old){const copy={...row,employee_name:name};by.set(key,copy);out.push(copy);continue;} for(const [target,keys] of [["oee",["oee","oee_pct","OEE"]],["performance",["performance","performance_pct","vykon","výkon"]],["available_time",["available_time","availability","availability_pct","dostupnost","dostupny_cas","dostupný čas"]]] as const) if(firstNum(old,keys)===null){const n=firstNum(row,keys);if(n!==null)old[target]=n;} if(!firstText(old,["position","operation","role","pozice"])){const pos=firstText(row,["position","operation","role","pozice"]);if(pos)old.position=pos;} } return out; }
function normalizeWorkDate(v: unknown): string|null { const raw=text(v); if(!raw)return null; const y=/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/.exec(raw.slice(0,10)); if(y)return `${y[1]}-${String(+y[2]).padStart(2,"0")}-${String(+y[3]).padStart(2,"0")}`; const d=/^(\d{1,2})[.\-/](\d{1,2})/.exec(raw); if(d){const now=new Date();return `${now.getFullYear()}-${String(+d[2]).padStart(2,"0")}-${String(+d[1]).padStart(2,"0")}`;} return null; }
function normalizeShift(v: unknown): string|null { const s=text(v).toLowerCase(); if(!s)return null; if(s.includes("rann")||s==="r"||s==="1")return "Ranní"; if(s.includes("odpo")||s==="o"||s==="2")return "Odpolední"; if(s.includes("noč")||s==="n"||s==="3")return "Noční"; return text(v); }
function actualOutputForHour(h: Record<string,unknown>): number|null { const actual=firstNum(h,["actual_output","actual","realny","real"]); if(actual!==null)return actual; return null; }
function calcOee(actual:number|null,norm:number|null,capacity:number|null,operators:number):number|null { if(actual===null||norm===null||capacity===null||norm<=0||capacity<=0||operators<=0)return null; return (actual/norm)*(capacity/operators)*100; }
function effectiveHourWeights(n:number):number[]{if(n<=0)return[];const w=Array.from({length:n},()=>1);if(n===1){w[0]=(SHIFT_MINUTES-START_PREP_MINUTES-BREAK_MINUTES-END_CLEANUP_MINUTES)/60;return w;}w[0]-=START_PREP_MINUTES/60;w[n-1]-=END_CLEANUP_MINUTES/60;if(n>=3)w[Math.floor(n/2)]-=BREAK_MINUTES/60;return w;}
function predictedShiftOutput(hourly:Record<string,unknown>[]):number|null{if(!hourly.length)return null;const w=effectiveHourWeights(hourly.length);let total=0,used=0;hourly.forEach((r,i)=>{const norm=firstNum(r,["norm_per_hour","norm","hourly_norm"]);const a=firstNum(r,["availability_pct","availability","dostupnost","dostupnost_pct"]);if(norm===null||a===null||a<=0)return;const full=norm/(a/100);if(!Number.isFinite(full)||full<=0)return;total+=full*w[i];used+=w[i];});return used>0?total:null;}
function normalizeProducts(parsed:Record<string,unknown>):OcrProduct[]{const hourly=Array.isArray(parsed.hourly_metrics)?parsed.hourly_metrics as Record<string,unknown>[]:[];const raw=Array.isArray(parsed.products)?parsed.products as Record<string,unknown>[]:[];const codes=new Set<string>();const add=(v:unknown)=>{const c=text(v);if(c)codes.add(c);};add(parsed.product_code);add(parsed.product);add(parsed.main_product);hourly.forEach(h=>add(firstText(h,["product_code","product"])));raw.forEach(p=>add(firstText(p,["product_code","product","code"])));return [...codes].map(code=>{const ai=raw.find(p=>firstText(p,["product_code","product","code"])===code);const hs=hourly.filter(h=>firstText(h,["product_code","product"])===code);const direct=hs.map(h=>firstNum(h,["norm_per_hour","norm","hourly_norm"])).find((v):v is number=>v!==null&&v>0&&hs.some(x=>firstNum(x,["availability_pct","availability","dostupnost"])===100));const fallback=hs.map(h=>{const n=firstNum(h,["norm_per_hour","norm","hourly_norm"]);const a=firstNum(h,["availability_pct","availability","dostupnost"]);return n!==null&&a!==null&&a>0?n/a*100:null;}).find((v):v is number=>v!==null&&v>0);const aiNorm=ai?firstNum(ai,["norm_per_hour","norm","hourly_norm"]):null;return{product_code:code,norm_per_hour:direct??fallback??aiNorm,confidence:ai?(firstNum(ai,["confidence","certainty"])??.85):.7};});}
function normalizeRows(parsed:Record<string,unknown>):OcrRow[]{const product=firstText(parsed,["product_code","product","main_product"]);const inferred: "HA"|"TUP"|null=(/^T_/i.test(product)?"TUP":/^H_/i.test(product)?"HA":null);const globalOee=firstNum(parsed,["line_oee","oee","shift_oee","oee_pct"]);return rawRowsFrom(parsed).map(r=>{const p=firstText(r,["product_code","product"])||product;const pr=firstText(r,["position","operation","role","pozice"]);const pos: "HA"|"TUP"|null=pr==="HA"||pr==="TUP"?pr:/^T_/i.test(p)?"TUP":/^H_/i.test(p)?"HA":inferred;const name=workerName(r);return{employee_name:name,position:pos,oee:firstNum(r,["oee","oee_pct","OEE"])??globalOee,performance:firstNum(r,["performance","performance_pct","vykon","výkon"]),available_time:firstNum(r,["available_time","availability","availability_pct","dostupnost","dostupny_cas","dostupný čas"]),confidence:firstNum(r,["confidence","certainty","jistota"])??(name?.8:.3)};}).filter(r=>r.employee_name);}

type AiProvider={kind:"openrouter"|"lovable";url:string;model:string;headers:Record<string,string>};
function resolveAiProviders():AiProvider[]{const p:AiProvider[]=[];const ok=process.env.OPENROUTER_API_KEY;if(ok)p.push({kind:"openrouter",url:"https://openrouter.ai/api/v1/chat/completions",model:process.env.OPENROUTER_MODEL??"qwen/qwen3-vl-8b-instruct",headers:{"Content-Type":"application/json",Authorization:`Bearer ${ok}`}});const lk=process.env.LOVABLE_API_KEY;if(lk)p.push({kind:"lovable",url:"https://ai.gateway.lovable.dev/v1/chat/completions",model:"google/gemini-3.6-flash",headers:{"Content-Type":"application/json","Lovable-API-Key":lk}});if(!p.length)throw new Error("Chybí konfigurace AI služby (OPENROUTER_API_KEY nebo LOVABLE_API_KEY). Rozpoznávání ze screenshotu není dostupné, ruční zadání funguje beze změny.");return p;}
async function callAi(provider:AiProvider,imageDataUrl:string,instruction:string,system=SYSTEM):Promise<Record<string,unknown>>{const res=await fetch(provider.url,{method:"POST",headers:provider.headers,body:JSON.stringify({model:provider.model,temperature:0,max_tokens:7000,response_format:{type:"json_object"},messages:[{role:"system",content:system},{role:"user",content:[{type:"text",text:instruction},{type:"image_url",image_url:{url:imageDataUrl}}]}]})});if(!res.ok){const body=await res.text();const e=new Error(`AI:${res.status}:${body.slice(0,300)}`) as Error&{status?:number};e.status=res.status;throw e;}const json=await res.json() as {choices?:{message?:{content?:string}}[]};const content=json.choices?.[0]?.message?.content??"";try{return JSON.parse(content.replace(/^```(?:json)?|```$/g,"").trim()) as Record<string,unknown>;}catch{throw new Error("AI vrátila neočekávanou JSON odpověď.");}}

const PRODUCT_STAGE_SYSTEM=`${SYSTEM}\nTENTO PRŮCHOD JE VÝHRADNĚ PRO PRODUKTY. Vrať Product ID, jejich normy a hlavičku. rows a hourly_metrics mohou být prázdné.`;
const EMPLOYEE_STAGE_SYSTEM=`${SYSTEM}\nTENTO PRŮCHOD JE VÝHRADNĚ PRO PRACOVNÍKY. Vrať každý viditelný řádek pracovníků. products a hourly_metrics mohou být prázdné.`;
const HOURLY_STAGE_SYSTEM=`${SYSTEM}\nTENTO PRŮCHOD JE VÝHRADNĚ PRO HODINOVÁ DATA. Vrať všechny viditelné hodinové řádky. Normu neber jako zdroj pro OEE; OEE spočítá aplikace z kontextu.`;

async function oneStage(stage:OcrStage,imageDataUrl:string,context?:OcrContext):Promise<OcrResult>{const providers=resolveAiProviders();const system=stage==="products"?PRODUCT_STAGE_SYSTEM:stage==="employees"?EMPLOYEE_STAGE_SYSTEM:HOURLY_STAGE_SYSTEM;let primary:Record<string,unknown>|null=null;let primaryProvider:AiProvider|null=null;const attempts:string[]=[];for(const provider of providers){try{primary=await callAi(provider,imageDataUrl,stage==="products"?"Přečti všechny Product ID, normy a hlavičku.":stage==="employees"?WORKER_RETRY:`Přečti všechny hodinové řádky. Kontext z předchozích sekvencí: Product ID=${context?.product_code??"null"}; norma=${context?.norm_per_hour??"null"} ks/h; kapacita=${context?.capacity??"null"} operátorů; skutečný počet operátorů=${context?.employee_count??0}. Počet operátorů je konstantní po celou směnu. Pouze přečti actual_output, performance_pct a availability_pct.`,system);primaryProvider=provider;break;}catch(e){const er=e as Error&{status?:number};attempts.push(`${provider.kind}:${er.status??"error"}`);if(er.status!==402&&er.status!==429)break;}}if(!primary||!primaryProvider)throw new Error(`AI služba je dočasně nedostupná (${attempts.join(" → ")}). Zkuste to prosím za chvíli.`);
 let parsedResults=[primary]; if(stage==="employees"){for(const provider of [primaryProvider,...providers.filter(p=>p!==primaryProvider)]){if(provider===primaryProvider&&rawRowsFrom(primary).some(r=>workerName(r)))continue;try{const retry=await callAi(provider,imageDataUrl,WORKER_RETRY,EMPLOYEE_STAGE_SYSTEM);parsedResults.push(retry);if(rawRowsFrom(retry).some(r=>workerName(r)))break;}catch(e){const er=e as Error&{status?:number};attempts.push(`worker-${provider.kind}:${er.status??"error"}`);if(er.status!==402&&er.status!==429)break;}}}
 const base=parsedResults.reduce((best,c)=>stage==="employees"?(workerScore(c)>workerScore(best)?c:best):best,primary);const rows=stage==="employees"?normalizeRows({...base,rows:mergeWorkerRows(...parsedResults.map(rawRowsFrom))}):[];const hourlyRaw=stage==="hourly"?(Array.isArray(primary.hourly_metrics)?primary.hourly_metrics as Record<string,unknown>[]:[]):[];const products=normalizeProducts({...base,hourly_metrics:hourlyRaw});const hourly:OcrHourlyMetric[]=hourlyRaw.map(h=>({hour:firstNum(h,["hour","hodina"]),product_code:firstText(h,["product_code","product"])||null,actual_output:actualOutputForHour(h),performance_pct:firstNum(h,["performance_pct","performance","vykon","výkon"]),availability_pct:firstNum(h,["availability_pct","availability","dostupnost","dostupnost_pct"]),norm_per_hour:context?.norm_per_hour??null,oee:stage==="hourly"?calcOee(actualOutputForHour(h),context?.norm_per_hour??null,context?.capacity??null,context?.employee_count??0):null}));
 return{work_date:normalizeWorkDate(firstText(base,["work_date","date"])),shift:normalizeShift(base.shift),line:firstText(base,["line","line_code"])||null,product_code:products[0]?.product_code??(firstText(base,["product_code","product","main_product"])||null),norm_per_hour:products[0]?.norm_per_hour??firstNum(base,["norm_per_hour","norm"]),products,header_confidence:Math.max(0,Math.min(1,firstNum(base,["header_confidence","confidence"])??.7)),rows,hourly_metrics:hourly,predicted_shift_output:stage==="hourly"?predictedShiftOutput(hourlyRaw):null,productive_minutes:hourlyRaw.length>=3?SHIFT_MINUTES-START_PREP_MINUTES-BREAK_MINUTES-END_CLEANUP_MINUTES:null,raw:JSON.stringify({stage,context,ocr_attempts:attempts})};}

async function runStage(stage:OcrStage,imageDataUrl:string,context?:OcrContext):Promise<OcrResult>{
 if(stage!=="hourly"||context)return oneStage(stage,imageDataUrl,context);
 const products=await oneStage("products",imageDataUrl);
 const employees=await oneStage("employees",imageDataUrl);
 const productCode=products.product_code??products.products[0]?.product_code??null;
 const product=products.products.find(p=>p.product_code===productCode)??products.products[0];
 const employeeCount=employees.rows.length;
 let capacity:number|null=null;
 let dbNorm:number|null=null;
 try {
   const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
   if (productCode) {
     const { data: dbProduct, error: productError } = await supabaseAdmin.from("products").select("id,employees_per_product").eq("code",productCode).maybeSingle();
     if (productError) throw productError;
     capacity = dbProduct?.employees_per_product ?? null;
     if (dbProduct?.id) {
       const operation: "HA"|"TUP" = /^T_/i.test(productCode) ? "TUP" : "HA";
       const { data: dbNormRow, error: normError } = await supabaseAdmin.from("product_norms").select("norm_per_hour").eq("product_id",dbProduct.id).eq("operation",operation).order("valid_from",{ascending:false}).limit(1).maybeSingle();
       if (normError) throw normError;
       dbNorm = dbNormRow?.norm_per_hour ?? null;
     }
   }
 } catch (e) {
   console.warn("OCR hourly context DB lookup failed", e);
 }
 return oneStage("hourly",imageDataUrl,{product_code:productCode,norm_per_hour:product?.norm_per_hour??dbNorm??products.norm_per_hour,capacity,employee_count:employeeCount});
}

export const extractScreenshotStage=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{imageDataUrl:string;stage:OcrStage;context?:OcrContext})=>{if(!input?.imageDataUrl?.startsWith("data:image/"))throw new Error("Neplatný obrázek.");if(!["products","employees","hourly"].includes(input.stage))throw new Error("Neplatná OCR fáze.");if(input.context&&(!Number.isInteger(input.context.employee_count)||input.context.employee_count<0))throw new Error("Neplatný počet operátorů.");return input;}).handler(async({data})=>runStage(data.stage,data.imageDataUrl,data.context));

export const extractDailyFromScreenshot=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((input:{imageDataUrl:string})=>{if(!input?.imageDataUrl?.startsWith("data:image/"))throw new Error("Neplatný obrázek.");return input;}).handler(async({data})=>{const products=await oneStage("products",data.imageDataUrl);const employees=await oneStage("employees",data.imageDataUrl);const product=products.products[0];return oneStage("hourly",data.imageDataUrl,{product_code:product?.product_code??products.product_code,norm_per_hour:product?.norm_per_hour??products.norm_per_hour,capacity:null,employee_count:employees.rows.length});});
