import { useMemo, useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { Check, ImageUp, Loader2, Plus, Trash2, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { extractScreenshotStage, type OcrProduct, type OcrResult, type OcrHourlyMetric } from "@/lib/ocr.functions";
import { extractHourlyWithContext } from "@/lib/ocr.hourly.functions";
import { useProductNorms, useProducts, useShiftAggregates } from "@/lib/data";
import { currentNorm, findProductByCode, type Product } from "@/lib/products";
import { SHIFTS, type Employee } from "@/lib/metrics";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useApprovalFields } from "@/lib/auth";

type DraftRow = { key: string; ocrName: string; employeeId: string | null; position: "HA" | "TUP"; oee: string; performance: string; availableTime: string; helpScore: string; confidence: number; include: boolean };
type DraftProduct = OcrProduct & { key: string; employees_per_product: number | null };
type ProductSetupDraft = { key: string; code: string; name: string; norm: string; capacity: string; confidence: number; counterpartCode: string; counterpartName: string; counterpartNorm: string; counterpartCapacity: string };
type ImportStage = "products" | "employees" | "hourly" | "ready";
const strip = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9 ]/g, "").trim();
function matchEmployee(name: string, employees: Employee[]): Employee | undefined { const n = strip(name); if (!n) return undefined; const exact = employees.find((e) => strip(e.full_name) === n); if (exact) return exact; const parts = n.split(/\s+/).filter(Boolean); return employees.find((e) => { const en = strip(e.full_name); return parts.length > 1 && parts.every((p) => en.includes(p)); }); }

export function ScreenshotImport({ employees, onImported }: { employees: Employee[]; onImported?: () => void }) {
  const qc = useQueryClient(); const approval = useApprovalFields(); const extractStage = useServerFn(extractScreenshotStage); const extractHourlyContext = useServerFn(extractHourlyWithContext);
  const { data: products = [] } = useProducts(); const { data: norms = [] } = useProductNorms(); const { records: existingRecords, shifts: existingShifts } = useShiftAggregates();
  const fileRef = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false); const [stage, setStage] = useState<ImportStage>("products"); const [result, setResult] = useState<OcrResult | null>(null); const [screenshotPath, setScreenshotPath] = useState<string | null>(null); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [workDate, setWorkDate] = useState(""); const [shift, setShift] = useState<string>(SHIFTS[0]); const [line, setLine] = useState(""); const [productCode, setProductCode] = useState(""); const [normValue, setNormValue] = useState(""); const [productDrafts, setProductDrafts] = useState<DraftProduct[]>([]); const [rows, setRows] = useState<DraftRow[]>([]);
  const [addedEmployees, setAddedEmployees] = useState<Employee[]>([]); const [employeeSetupOpen, setEmployeeSetupOpen] = useState(false); const [addEmployeeOpen, setAddEmployeeOpen] = useState(false); const [addEmployeeRowKey, setAddEmployeeRowKey] = useState<string | null>(null); const [addEmployeeName, setAddEmployeeName] = useState(""); const [addEmployeePersonalNo, setAddEmployeePersonalNo] = useState("");
  const [newProductModalOpen, setNewProductModalOpen] = useState(false); const [productSetupSaving, setProductSetupSaving] = useState(false); const [productSetupDrafts, setProductSetupDrafts] = useState<ProductSetupDraft[]>([]); const [createdProducts, setCreatedProducts] = useState<Product[]>([]); const [productIdName, setProductIdName] = useState(""); const [hourlyMetrics, setHourlyMetrics] = useState<OcrHourlyMetric[]>([]);
  const activeEmployees = useMemo(() => [...employees, ...addedEmployees].filter((e) => e.active), [employees, addedEmployees]);
  const allProducts = useMemo(() => { const byCode = new Map<string, Product>(); [...products, ...createdProducts].forEach((p) => byCode.set(p.code.trim().toLowerCase(), p)); return Array.from(byCode.values()); }, [products, createdProducts]);
  const normNum = normValue === "" ? null : Number(normValue); const missingProductCodes = useMemo(() => productDrafts.filter((p) => !findProductByCode(allProducts, p.product_code)).map((p) => p.product_code), [productDrafts, allProducts]);
  const patch = (key: string, p: Partial<DraftRow>) => setRows((prev) => prev.map((r) => (r.key === key ? { ...r, ...p } : r)));
  const reset = () => { setStage("products"); setResult(null); setHourlyMetrics([]); setEmployeeSetupOpen(false); setRows([]); setProductDrafts([]); setScreenshotPath(null); setPreviewUrl(null); setProductCode(""); setNormValue(""); setAddedEmployees([]); setAddEmployeeOpen(false); setAddEmployeeRowKey(null); setAddEmployeeName(""); setAddEmployeePersonalNo(""); setNewProductModalOpen(false); setProductSetupSaving(false); setProductSetupDrafts([]); setCreatedProducts([]); if (fileRef.current) fileRef.current.value = ""; };
  const openAddEmployee = (row: DraftRow) => { setAddEmployeeRowKey(row.key); setAddEmployeeName(row.ocrName.trim()); setAddEmployeePersonalNo(""); setAddEmployeeOpen(true); };
  const createEmployee = useMutation({ mutationFn: async () => { const fullName = addEmployeeName.trim(); const personalNo = addEmployeePersonalNo.trim(); if (!fullName) throw new Error("Zadejte jméno zaměstnance."); if (personalNo) { const { data: byPersonalNo, error: lookupError } = await supabase.from("employees").select("*").eq("personal_no", personalNo).maybeSingle(); if (lookupError) throw lookupError; if (byPersonalNo) return byPersonalNo as Employee; } const existing = matchEmployee(fullName, [...employees, ...addedEmployees]); if (existing) return existing; const payload = { full_name: fullName, personal_no: personalNo || null, qual_ha: false, qual_tup: false, active: true, is_temporary: false, position_type: "standard" as const, note: null }; const { data, error } = await supabase.from("employees").insert(payload).select("*").single(); if (error) throw error; if (!data) throw new Error("Zaměstnanec byl uložen, ale nepodařilo se načíst vytvořený záznam."); return data as Employee; }, onSuccess: (employee) => { setAddedEmployees((prev) => prev.some((e) => e.id === employee.id) ? prev : [...prev, employee]); if (addEmployeeRowKey) patch(addEmployeeRowKey, { employeeId: employee.id }); qc.invalidateQueries({ queryKey: ["employees"] }); setAddEmployeeOpen(false); setAddEmployeeRowKey(null); setAddEmployeeName(""); setAddEmployeePersonalNo(""); toast.success(`Zaměstnanec „${employee.full_name}" byl přidán a přiřazen k řádku importu.`); }, onError: (e: Error) => toast.error(`Zaměstnance se nepodařilo přidat: ${e.message}`) });
  const openProductSetup = (detected: DraftProduct[]) => { setProductIdName(""); const detectedCodes = new Set(detected.map((p) => p.product_code.trim().toLowerCase())); const missing = Array.from(new Set(detected.map((p) => p.product_code.trim()).filter(Boolean))).filter((code) => !findProductByCode(allProducts, code)); const detectedByCode = new Map(detected.map((p) => [p.product_code.trim().toLowerCase(), p])); setProductSetupDrafts(missing.map((code, i) => { const detectedProduct = detectedByCode.get(code.toLowerCase()); const isH = /^H_/i.test(code); const isT = /^T_/i.test(code); const oppositeDetected = isH ? Array.from(detectedCodes).some((x) => /^T_/i.test(x)) : isT ? Array.from(detectedCodes).some((x) => /^H_/i.test(x)) : false; return { key: i + "-" + code, code, name: "", norm: detectedProduct?.norm_per_hour != null ? String(detectedProduct.norm_per_hour) : "", capacity: "1", confidence: detectedProduct?.confidence ?? 0.5, counterpartCode: oppositeDetected ? "" : "", counterpartName: "", counterpartNorm: "", counterpartCapacity: "1" }; })); setNewProductModalOpen(true); };
  const createProductIds = async () => { if (!productSetupDrafts.length) return; setProductSetupSaving(true); try { const date = workDate || new Date().toISOString().slice(0, 10); const created: Product[] = []; const items: Array<{ code: string; name: string; norm: string; capacity: string; confidence: number; primary: boolean; sourceKey: string }> = []; const seen = new Set<string>(); for (const draft of productSetupDrafts) { const add = (code: string, name: string, norm: string, capacity: string, primary: boolean) => { const normalized = code.trim().toLowerCase(); if (!normalized || seen.has(normalized)) return; seen.add(normalized); items.push({ code: code.trim(), name: name.trim(), norm, capacity, confidence: draft.confidence, primary, sourceKey: draft.key }); }; add(draft.code, draft.name, draft.norm, draft.capacity, true); if (draft.counterpartCode.trim()) add(draft.counterpartCode, draft.counterpartName, draft.counterpartNorm, draft.counterpartCapacity, false); }
    for (const item of items) { const code = item.code; const norm = Number(item.norm); const capacity = Number(item.capacity); if (!code) throw new Error("Každý Product ID musí mít kód."); let product = findProductByCode(allProducts, code) ?? created.find((p) => p.code.trim().toLowerCase() === code.toLowerCase()); const existedBefore = Boolean(product); if (!product) { if (!Number.isFinite(norm) || norm <= 0) throw new Error("Zadejte platnou normu pro " + code + "."); if (!Number.isInteger(capacity) || capacity < 1) throw new Error("Zadejte platnou kapacitu operátorů pro " + code + "."); const { data, error } = await supabase.from("products").insert({ code, name: item.name || productIdName.trim(), employees_per_product: capacity, first_seen_date: date, ...approval() }).select("*").single(); if (error) throw error; product = data as Product; const operation: "HA" | "TUP" = /^T_/i.test(code) ? "TUP" : "HA"; const { error: normError } = await supabase.from("product_norms").insert({ product_id: product.id, operation, norm_per_hour: norm, valid_from: date, source: "screenshot", confirmed: true, note: "Norma vytvořená při importu screenshotu", ...approval() }); if (normError) throw normError; } else if (item.primary && item.name) { const { data, error } = await supabase.from("products").update({ name: item.name, employees_per_product: Number.isInteger(capacity) && capacity >= 1 ? capacity : product.employees_per_product }).eq("id", product.id).select("*").single(); if (error) throw error; product = data as Product; } if (!existedBefore || item.primary) created.push(product); }
    const productByCode = new Map<string, Product>(); [...allProducts, ...created].forEach((p) => productByCode.set(p.code.trim().toLowerCase(), p)); for (const draft of productSetupDrafts) { const hCode = /^H_/i.test(draft.code) ? draft.code.trim() : draft.counterpartCode.trim(); const tCode = /^T_/i.test(draft.code) ? draft.code.trim() : draft.counterpartCode.trim(); if (!hCode || !tCode || !/^H_/i.test(hCode) || !/^T_/i.test(tCode)) continue; const hProduct = productByCode.get(hCode.toLowerCase()); const tProduct = productByCode.get(tCode.toLowerCase()); if (!hProduct || !tProduct || hProduct.id === tProduct.id) continue; const { data: existingFamily, error: familyLookupError } = await (supabase.from("product_families") as any).select("id,h_product_id,t_product_id,name").or("h_product_id.eq." + hProduct.id + ",t_product_id.eq." + tProduct.id).maybeSingle(); if (familyLookupError && !/does not exist|relation/i.test(familyLookupError.message)) throw familyLookupError; if (!existingFamily) { const familyName = productIdName.trim(); if (!familyName) throw new Error("Zadejte název Product ID."); const { data: family, error: familyError } = await (supabase.from("product_families") as any).insert({ name: familyName, h_product_id: hProduct.id, t_product_id: tProduct.id }).select("*").single(); if (familyError) throw familyError; const { error: hLinkError } = await (supabase.from("products") as any).update({ family_id: family.id, variant_type: "H" }).eq("id", hProduct.id); if (hLinkError) throw hLinkError; const { error: tLinkError } = await (supabase.from("products") as any).update({ family_id: family.id, variant_type: "T" }).eq("id", tProduct.id); if (tLinkError) throw tLinkError; } }
    setCreatedProducts((prev) => { const byCode = new Map(prev.map((p) => [p.code.trim().toLowerCase(), p])); created.forEach((p) => byCode.set(p.code.trim().toLowerCase(), p)); return Array.from(byCode.values()); }); setProductDrafts((prev) => prev.map((p) => { const setup = productSetupDrafts.find((d) => d.code.trim().toLowerCase() === p.product_code.trim().toLowerCase()); return setup ? { ...p, norm_per_hour: Number(setup.norm), employees_per_product: Number(setup.capacity) } : p; })); setNewProductModalOpen(false); qc.invalidateQueries({ queryKey: ["products"] }); qc.invalidateQueries({ queryKey: ["product_norms"] }); toast.success(`Zkontrolováno / založeno ${created.length} Product ID. Pokračuji na zaměstnance.`); if (previewUrl) void runEmployeeStage(previewUrl); } finally { setProductSetupSaving(false); } };
  const runEmployeeStage = async (imageDataUrl: string) => { setBusy(true); setStage("employees"); try { const r = await extractStage({ data: { imageDataUrl, stage: "employees" } }); const { data: dbEmployees, error: employeeLoadError } = await supabase.from("employees").select("*").eq("active", true); if (employeeLoadError) throw employeeLoadError; const freshEmployees = (dbEmployees ?? []) as Employee[]; const employeePool = [...freshEmployees, ...addedEmployees]; setResult((prev) => ({ ...(prev ?? r), work_date: prev?.work_date ?? r.work_date, shift: prev?.shift ?? r.shift, line: prev?.line ?? r.line, product_code: prev?.product_code ?? r.product_code, norm_per_hour: prev?.norm_per_hour ?? r.norm_per_hour, products: prev?.products?.length ? prev.products : r.products, header_confidence: Math.max(prev?.header_confidence ?? 0, r.header_confidence), rows: r.rows, hourly_metrics: prev?.hourly_metrics ?? [], predicted_shift_output: prev?.predicted_shift_output ?? null, productive_minutes: prev?.productive_minutes ?? null })); const fallbackPosition: "HA" | "TUP" = productDrafts.some((p) => /^T_/i.test(p.product_code)) ? "TUP" : "HA"; const nextRows: DraftRow[] = r.rows.map((row, i) => { const emp = matchEmployee(row.employee_name, employeePool); return { key: i + "-" + (row.employee_name || "manual"), ocrName: row.employee_name, employeeId: emp?.id ?? null, position: row.position ?? fallbackPosition, oee: row.oee !== null ? String(row.oee) : "", performance: row.performance !== null ? String(row.performance) : "", availableTime: row.available_time !== null ? String(row.available_time) : "", helpScore: "0", confidence: row.confidence, include: true }; }); setRows(nextRows); if (!nextRows.length || nextRows.some((r) => r.include && !r.employeeId)) { setEmployeeSetupOpen(true); if (!nextRows.length) toast.warning("OCR zaměstnanců nevrátil žádný čitelný řádek. Hodinová data se zatím nespustí."); } else await runHourlyStage(imageDataUrl, nextRows); } catch (e) { toast.error("OCR zaměstnanců se nepodařilo dokončit: " + (e as Error).message); setStage("employees"); } finally { setBusy(false); } };
  const runHourlyStage = async (imageDataUrl: string, employeeRows: DraftRow[] = rows) => { setBusy(true); setStage("hourly"); try {
    const contextProducts = productDrafts.map((draft) => {
      const code = draft.product_code.trim();
      const setup = productSetupDrafts.find((d) => d.code.trim().toLowerCase() === code.toLowerCase());
      const product = findProductByCode(allProducts, code);
      const operation: "HA" | "TUP" = /^T_/i.test(code) ? "TUP" : "HA";
      const dbNorm = product ? currentNorm(norms, product.id, operation)?.norm_per_hour ?? null : null;
      const contextNorm = setup?.norm ? Number(setup.norm) : draft.norm_per_hour;
      const norm = dbNorm ?? contextNorm ?? null;
      const capacity = product?.employees_per_product ?? (setup?.capacity ? Number(setup.capacity) : draft.employees_per_product);
      return { product_code: code, norm_per_hour: norm, capacity: capacity ?? null };
    });
    if (missingProductCodes.length) throw new Error("Nejprve dokončete kontrolu/založení všech Product ID v prvním kroku.");
    const operatorCount = employeeRows.filter((r) => r.include && r.employeeId).length;
    if (operatorCount < 1) throw new Error("3. sekvence potřebuje alespoň jednoho skutečného operátora z 2. sekvence.");
    const profiles = contextProducts.map((p) => ({ id: p.product_code, ha_subassy: /^H_/i.test(p.product_code) ? p.product_code : null, h_capacity: /^H_/i.test(p.product_code) ? p.capacity : null, h_norm_per_hour: /^H_/i.test(p.product_code) ? p.norm_per_hour : null, tup_subassy: /^T_/i.test(p.product_code) ? p.product_code : null, t_capacity: /^T_/i.test(p.product_code) ? p.capacity : null, t_norm_per_hour: /^T_/i.test(p.product_code) ? p.norm_per_hour : null }));
    const r = await extractHourlyContext({ data: { imageDataUrl, context: { profiles, products: contextProducts, operator_count: operatorCount } } });
    setHourlyMetrics(r.hourly_metrics); setResult((prev) => prev ? { ...prev, hourly_metrics: r.hourly_metrics, predicted_shift_output: r.predicted_shift_output, productive_minutes: prev.productive_minutes } : prev); setStage("ready");
  } catch (e) { toast.error("OCR hodinových dat se nepodařilo dokončit: " + (e as Error).message); setStage("hourly"); } finally { setBusy(false); } };
