/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzaRouteImport } from './routes/analyza'
import { Route as DenniDataRouteImport } from './routes/denni-data'
import { Route as KeSchvaleniRouteImport } from './routes/ke-schvaleni'
import { Route as MojeVysledkyRouteImport } from './routes/moje-vysledky'
import { Route as OAplikaciRouteImport } from './routes/o-aplikaci'
import { Route as PremereniNoremRouteImport } from './routes/premereni-norem'
import { Route as ProduktyRouteImport } from './routes/produkty'
import { Route as QualityAlertyRouteImport } from './routes/quality-alerty'
import { Route as ReportyRouteImport } from './routes/reporty'
import { Route as TydenniDataRouteImport } from './routes/tydenni-data'
import { Route as UzivateleRouteImport } from './routes/uzivatele'
import { Route as ZamestnanciRouteImport } from './routes/zamestnanci'
import { Route as ZebricekRouteImport } from './routes/zebricek'
import { Route as ZamestnanecIdRouteImport } from './routes/zamestnanec.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzaRoute = AnalyzaRouteImport.update({
  id: '/analyza',
  path: '/analyza',
  getParentRoute: () => rootRouteImport,
} as any)
const DenniDataRoute = DenniDataRouteImport.update({
  id: '/denni-data',
  path: '/denni-data',
  getParentRoute: () => rootRouteImport,
} as any)
const KeSchvaleniRoute = KeSchvaleniRouteImport.update({
  id: '/ke-schvaleni',
  path: '/ke-schvaleni',
  getParentRoute: () => rootRouteImport,
} as any)
const MojeVysledkyRoute = MojeVysledkyRouteImport.update({
  id: '/moje-vysledky',
  path: '/moje-vysledky',
  getParentRoute: () => rootRouteImport,
} as any)
const OAplikaciRoute = OAplikaciRouteImport.update({
  id: '/o-aplikaci',
  path: '/o-aplikaci',
  getParentRoute: () => rootRouteImport,
} as any)
const PremereniNoremRoute = PremereniNoremRouteImport.update({
  id: '/premereni-norem',
  path: '/premereni-norem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyRoute = ProduktyRouteImport.update({
  id: '/produkty',
  path: '/produkty',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityAlertyRoute = QualityAlertyRouteImport.update({
  id: '/quality-alerty',
  path: '/quality-alerty',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportyRoute = ReportyRouteImport.update({
  id: '/reporty',
  path: '/reporty',
  getParentRoute: () => rootRouteImport,
} as any)
const TydenniDataRoute = TydenniDataRouteImport.update({
  id: '/tydenni-data',
  path: '/tydenni-data',
  getParentRoute: () => rootRouteImport,
} as any)
const UzivateleRoute = UzivateleRouteImport.update({
  id: '/uzivatele',
  path: '/uzivatele',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamestnanciRoute = ZamestnanciRouteImport.update({
  id: '/zamestnanci',
  path: '/zamestnanci',
  getParentRoute: () => rootRouteImport,
} as any)
const ZebricekRoute = ZebricekRouteImport.update({
  id: '/zebricek',
  path: '/zebricek',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamestnanecIdRoute = ZamestnanecIdRouteImport.update({
  id: '/zamestnanec/$id',
  path: '/zamestnanec/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyza': typeof AnalyzaRoute
  '/denni-data': typeof DenniDataRoute
  '/ke-schvaleni': typeof KeSchvaleniRoute
  '/moje-vysledky': typeof MojeVysledkyRoute
  '/o-aplikaci': typeof OAplikaciRoute
  '/premereni-norem': typeof PremereniNoremRoute
  '/produkty': typeof ProduktyRoute
  '/quality-alerty': typeof QualityAlertyRoute
  '/reporty': typeof ReportyRoute
  '/tydenni-data': typeof TydenniDataRoute
  '/uzivatele': typeof UzivateleRoute
  '/zamestnanci': typeof ZamestnanciRoute
  '/zebricek': typeof ZebricekRoute
  '/zamestnanec/$id': typeof ZamestnanecIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyza': typeof AnalyzaRoute
  '/denni-data': typeof DenniDataRoute
  '/ke-schvaleni': typeof KeSchvaleniRoute
  '/moje-vysledky': typeof MojeVysledkyRoute
  '/o-aplikaci': typeof OAplikaciRoute
  '/premereni-norem': typeof PremereniNoremRoute
  '/produkty': typeof ProduktyRoute
  '/quality-alerty': typeof QualityAlertyRoute
  '/reporty': typeof ReportyRoute
  '/tydenni-data': typeof TydenniDataRoute
  '/uzivatele': typeof UzivateleRoute
  '/zamestnanci': typeof ZamestnanciRoute
  '/zebricek': typeof ZebricekRoute
  '/zamestnanec/$id': typeof ZamestnanecIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyza': typeof AnalyzaRoute
  '/denni-data': typeof DenniDataRoute
  '/ke-schvaleni': typeof KeSchvaleniRoute
  '/moje-vysledky': typeof MojeVysledkyRoute
  '/o-aplikaci': typeof OAplikaciRoute
  '/premereni-norem': typeof PremereniNoremRoute
  '/produkty': typeof ProduktyRoute
  '/quality-alerty': typeof QualityAlertyRoute
  '/reporty': typeof ReportyRoute
  '/tydenni-data': typeof TydenniDataRoute
  '/uzivatele': typeof UzivateleRoute
  '/zamestnanci': typeof ZamestnanciRoute
  '/zebricek': typeof ZebricekRoute
  '/zamestnanec/$id': typeof ZamestnanecIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyza'
    | '/denni-data'
    | '/ke-schvaleni'
    | '/moje-vysledky'
    | '/o-aplikaci'
    | '/premereni-norem'
    | '/produkty'
    | '/quality-alerty'
    | '/reporty'
    | '/tydenni-data'
    | '/uzivatele'
    | '/zamestnanci'
    | '/zebricek'
    | '/zamestnanec/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyza'
    | '/denni-data'
    | '/ke-schvaleni'
    | '/moje-vysledky'
    | '/o-aplikaci'
    | '/premereni-norem'
    | '/produkty'
    | '/quality-alerty'
    | '/reporty'
    | '/tydenni-data'
    | '/uzivatele'
    | '/zamestnanci'
    | '/zebricek'
    | '/zamestnanec/$id'
  id:
    | '__root__'
    | '/'
    | '/analyza'
    | '/denni-data'
    | '/ke-schvaleni'
    | '/moje-vysledky'
    | '/o-aplikaci'
    | '/premereni-norem'
    | '/produkty'
    | '/quality-alerty'
    | '/reporty'
    | '/tydenni-data'
    | '/uzivatele'
    | '/zamestnanci'
    | '/zebricek'
    | '/zamestnanec/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzaRoute: typeof AnalyzaRoute
  DenniDataRoute: typeof DenniDataRoute
  KeSchvaleniRoute: typeof KeSchvaleniRoute
  MojeVysledkyRoute: typeof MojeVysledkyRoute
  OAplikaciRoute: typeof OAplikaciRoute
  PremereniNoremRoute: typeof PremereniNoremRoute
  ProduktyRoute: typeof ProduktyRoute
  QualityAlertyRoute: typeof QualityAlertyRoute
  ReportyRoute: typeof ReportyRoute
  TydenniDataRoute: typeof TydenniDataRoute
  UzivateleRoute: typeof UzivateleRoute
  ZamestnanciRoute: typeof ZamestnanciRoute
  ZebricekRoute: typeof ZebricekRoute
  ZamestnanecIdRoute: typeof ZamestnanecIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyza': {
      id: '/analyza'
      path: '/analyza'
      fullPath: '/analyza'
      preLoaderRoute: typeof AnalyzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denni-data': {
      id: '/denni-data'
      path: '/denni-data'
      fullPath: '/denni-data'
      preLoaderRoute: typeof DenniDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ke-schvaleni': {
      id: '/ke-schvaleni'
      path: '/ke-schvaleni'
      fullPath: '/ke-schvaleni'
      preLoaderRoute: typeof KeSchvaleniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moje-vysledky': {
      id: '/moje-vysledky'
      path: '/moje-vysledky'
      fullPath: '/moje-vysledky'
      preLoaderRoute: typeof MojeVysledkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-aplikaci': {
      id: '/o-aplikaci'
      path: '/o-aplikaci'
      fullPath: '/o-aplikaci'
      preLoaderRoute: typeof OAplikaciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premereni-norem': {
      id: '/premereni-norem'
      path: '/premereni-norem'
      fullPath: '/premereni-norem'
      preLoaderRoute: typeof PremereniNoremRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty': {
      id: '/produkty'
      path: '/produkty'
      fullPath: '/produkty'
      preLoaderRoute: typeof ProduktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-alerty': {
      id: '/quality-alerty'
      path: '/quality-alerty'
      fullPath: '/quality-alerty'
      preLoaderRoute: typeof QualityAlertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporty': {
      id: '/reporty'
      path: '/reporty'
      fullPath: '/reporty'
      preLoaderRoute: typeof ReportyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tydenni-data': {
      id: '/tydenni-data'
      path: '/tydenni-data'
      fullPath: '/tydenni-data'
      preLoaderRoute: typeof TydenniDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uzivatele': {
      id: '/uzivatele'
      path: '/uzivatele'
      fullPath: '/uzivatele'
      preLoaderRoute: typeof UzivateleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamestnanci': {
      id: '/zamestnanci'
      path: '/zamestnanci'
      fullPath: '/zamestnanci'
      preLoaderRoute: typeof ZamestnanciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zebricek': {
      id: '/zebricek'
      path: '/zebricek'
      fullPath: '/zebricek'
      preLoaderRoute: typeof ZebricekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamestnanec/$id': {
      id: '/zamestnanec/$id'
      path: '/zamestnanec/$id'
      fullPath: '/zamestnanec/$id'
      preLoaderRoute: typeof ZamestnanecIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzaRoute: AnalyzaRoute,
  DenniDataRoute: DenniDataRoute,
  KeSchvaleniRoute: KeSchvaleniRoute,
  MojeVysledkyRoute: MojeVysledkyRoute,
  OAplikaciRoute: OAplikaciRoute,
  PremereniNoremRoute: PremereniNoremRoute,
  ProduktyRoute: ProduktyRoute,
  QualityAlertyRoute: QualityAlertyRoute,
  ReportyRoute: ReportyRoute,
  TydenniDataRoute: TydenniDataRoute,
  UzivateleRoute: UzivateleRoute,
  ZamestnanciRoute: ZamestnanciRoute,
  ZebricekRoute: ZebricekRoute,
  ZamestnanecIdRoute: ZamestnanecIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
