/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzaRouteImport } from './routes/analyza'
import { Route as AnomalieRouteImport } from './routes/anomalie'
import { Route as DenniDataRouteImport } from './routes/denni-data'
import { Route as GrafyRouteImport } from './routes/grafy'
import { Route as HodnoceniRouteImport } from './routes/hodnoceni'
import { Route as HromadnyPrepocetRouteImport } from './routes/hromadny-prepocet'
import { Route as InteraktivniRouteRouteImport } from './routes/interaktivni/route'
import { Route as KeSchvaleniRouteImport } from './routes/ke-schvaleni'
import { Route as MojeVysledkyRouteImport } from './routes/moje-vysledky'
import { Route as OAplikaciRouteImport } from './routes/o-aplikaci'
import { Route as OdstavkyRouteImport } from './routes/odstavky'
import { Route as PracovisteRouteImport } from './routes/pracoviste'
import { Route as PremereniNoremRouteImport } from './routes/premereni-norem'
import { Route as ProduktyRouteImport } from './routes/produkty'
import { Route as QualityAlertyRouteImport } from './routes/quality-alerty'
import { Route as ReportyRouteImport } from './routes/reporty'
import { Route as TydenniDataRouteImport } from './routes/tydenni-data'
import { Route as UzivateleRouteImport } from './routes/uzivatele'
import { Route as ZamestnanciRouteImport } from './routes/zamestnanci'
import { Route as ZebricekRouteImport } from './routes/zebricek'
import { Route as InteraktivniMapaRouteImport } from './routes/interaktivni/mapa'
import { Route as InteraktivniPracovisteMapaRouteImport } from './routes/interaktivni/pracoviste-mapa'
import { Route as InteraktivniSmenaObsazeniRouteImport } from './routes/interaktivni/smena-obsazeni'
import { Route as InteraktivniSmenaVyrobaRouteImport } from './routes/interaktivni/smena-vyroba'
import { Route as InteraktivniTymyRouteImport } from './routes/interaktivni/tymy'
import { Route as ZamestnanecIdRouteImport } from './routes/zamestnanec.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzaRoute = AnalyzaRouteImport.update({
  id: '/analyza',
  path: '/analyza',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalieRoute = AnomalieRouteImport.update({
  id: '/anomalie',
  path: '/anomalie',
  getParentRoute: () => rootRouteImport,
} as any)
const DenniDataRoute = DenniDataRouteImport.update({
  id: '/denni-data',
  path: '/denni-data',
  getParentRoute: () => rootRouteImport,
} as any)
const GrafyRoute = GrafyRouteImport.update({
  id: '/grafy',
  path: '/grafy',
  getParentRoute: () => rootRouteImport,
} as any)
const HodnoceniRoute = HodnoceniRouteImport.update({
  id: '/hodnoceni',
  path: '/hodnoceni',
  getParentRoute: () => rootRouteImport,
} as any)
const HromadnyPrepocetRoute = HromadnyPrepocetRouteImport.update({
  id: '/hromadny-prepocet',
  path: '/hromadny-prepocet',
  getParentRoute: () => rootRouteImport,
} as any)
const InteraktivniRouteRoute = InteraktivniRouteRouteImport.update({
  id: '/interaktivni',
  path: '/interaktivni',
  getParentRoute: () => rootRouteImport,
} as any)
const KeSchvaleniRoute = KeSchvaleniRouteImport.update({
  id: '/ke-schvaleni',
  path: '/ke-schvaleni',
  getParentRoute: () => rootRouteImport,
} as any)
const MojeVysledkyRoute = MojeVysledkyRouteImport.update({
  id: '/moje-vysledky',
  path: '/moje-vysledky',
  getParentRoute: () => rootRouteImport,
} as any)
const OAplikaciRoute = OAplikaciRouteImport.update({
  id: '/o-aplikaci',
  path: '/o-aplikaci',
  getParentRoute: () => rootRouteImport,
} as any)
const OdstavkyRoute = OdstavkyRouteImport.update({
  id: '/odstavky',
  path: '/odstavky',
  getParentRoute: () => rootRouteImport,
} as any)
const PracovisteRoute = PracovisteRouteImport.update({
  id: '/pracoviste',
  path: '/pracoviste',
  getParentRoute: () => rootRouteImport,
} as any)
const PremereniNoremRoute = PremereniNoremRouteImport.update({
  id: '/premereni-norem',
  path: '/premereni-norem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyRoute = ProduktyRouteImport.update({
  id: '/produkty',
  path: '/produkty',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityAlertyRoute = QualityAlertyRouteImport.update({
  id: '/quality-alerty',
  path: '/quality-alerty',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportyRoute = ReportyRouteImport.update({
  id: '/reporty',
  path: '/reporty',
  getParentRoute: () => rootRouteImport,
} as any)
const TydenniDataRoute = TydenniDataRouteImport.update({
  id: '/tydenni-data',
  path: '/tydenni-data',
  getParentRoute: () => rootRouteImport,
} as any)
const UzivateleRoute = UzivateleRouteImport.update({
  id: '/uzivatele',
  path: '/uzivatele',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamestnanciRoute = ZamestnanciRouteImport.update({
  id: '/zamestnanci',
  path: '/zamestnanci',
  getParentRoute: () => rootRouteImport,
} as any)
const ZebricekRoute = ZebricekRouteImport.update({
  id: '/zebricek',
  path: '/zebricek',
  getParentRoute: () => rootRouteImport,
} as any)
const InteraktivniMapaRoute = InteraktivniMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => InteraktivniRouteRoute,
} as any)
const InteraktivniPracovisteMapaRoute =
  InteraktivniPracovisteMapaRouteImport.update({
    id: '/pracoviste-mapa',
    path: '/pracoviste-mapa',
    getParentRoute: () => InteraktivniRouteRoute,
  } as any)
const InteraktivniSmenaObsazeniRoute =
  InteraktivniSmenaObsazeniRouteImport.update({
    id: '/smena-obsazeni',
    path: '/smena-obsazeni',
    getParentRoute: () => InteraktivniRouteRoute,
  } as any)
const InteraktivniSmenaVyrobaRoute = InteraktivniSmenaVyrobaRouteImport.update({
  id: '/smena-vyroba',
  path: '/smena-vyroba',
  getParentRoute: () => InteraktivniRouteRoute,
} as any)
const InteraktivniTymyRoute = InteraktivniTymyRouteImport.update({
  id: '/tymy',
  path: '/tymy',
  getParentRoute: () => InteraktivniRouteRoute,
} as any)
const ZamestnanecIdRoute = ZamestnanecIdRouteImport.update({
  id: '/zamestnanec/$id',
  path: '/zamestnanec/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interaktivni': typeof InteraktivniRouteRouteWithChildren
  '/analyza': typeof AnalyzaRoute
  '/anomalie': typeof AnomalieRoute
  '/denni-data': typeof DenniDataRoute
  '/grafy': typeof GrafyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/hromadny-prepocet': typeof HromadnyPrepocetRoute
  '/ke-schvaleni': typeof KeSchvaleniRoute
  '/moje-vysledky': typeof MojeVysledkyRoute
  '/o-aplikaci': typeof OAplikaciRoute
  '/odstavky': typeof OdstavkyRoute
  '/pracoviste': typeof PracovisteRoute
  '/premereni-norem': typeof PremereniNoremRoute
  '/produkty': typeof ProduktyRoute
  '/quality-alerty': typeof QualityAlertyRoute
  '/reporty': typeof ReportyRoute
  '/tydenni-data': typeof TydenniDataRoute
  '/uzivatele': typeof UzivateleRoute
  '/zamestnanci': typeof ZamestnanciRoute
  '/zebricek': typeof ZebricekRoute
  '/interaktivni/mapa': typeof InteraktivniMapaRoute
  '/interaktivni/pracoviste-mapa': typeof InteraktivniPracovisteMapaRoute
  '/interaktivni/smena-obsazeni': typeof InteraktivniSmenaObsazeniRoute
  '/interaktivni/smena-vyroba': typeof InteraktivniSmenaVyrobaRoute
  '/interaktivni/tymy': typeof InteraktivniTymyRoute
  '/zamestnanec/$id': typeof ZamestnanecIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interaktivni': typeof InteraktivniRouteRouteWithChildren
  '/analyza': typeof AnalyzaRoute
  '/anomalie': typeof AnomalieRoute
  '/denni-data': typeof DenniDataRoute
  '/grafy': typeof GrafyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/hromadny-prepocet': typeof HromadnyPrepocetRoute
  '/ke-schvaleni': typeof KeSchvaleniRoute
  '/moje-vysledky': typeof MojeVysledkyRoute
  '/o-aplikaci': typeof OAplikaciRoute
  '/odstavky': typeof OdstavkyRoute
  '/pracoviste': typeof PracovisteRoute
  '/premereni-norem': typeof PremereniNoremRoute
  '/produkty': typeof ProduktyRoute
  '/quality-alerty': typeof QualityAlertyRoute
  '/reporty': typeof ReportyRoute
  '/tydenni-data': typeof TydenniDataRoute
  '/uzivatele': typeof UzivateleRoute
  '/zamestnanci': typeof ZamestnanciRoute
  '/zebricek': typeof ZebricekRoute
  '/interaktivni/mapa': typeof InteraktivniMapaRoute
  '/interaktivni/pracoviste-mapa': typeof InteraktivniPracovisteMapaRoute
  '/interaktivni/smena-obsazeni': typeof InteraktivniSmenaObsazeniRoute
  '/interaktivni/smena-vyroba': typeof InteraktivniSmenaVyrobaRoute
  '/interaktivni/tymy': typeof InteraktivniTymyRoute
  '/zamestnanec/$id': typeof ZamestnanecIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interaktivni': typeof InteraktivniRouteRouteWithChildren
  '/analyza': typeof AnalyzaRoute
  '/anomalie': typeof AnomalieRoute
  '/denni-data': typeof DenniDataRoute
  '/grafy': typeof GrafyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/hromadny-prepocet': typeof HromadnyPrepocetRoute
  '/ke-schvaleni': typeof KeSchvaleniRoute
  '/moje-vysledky': typeof MojeVysledkyRoute
  '/o-aplikaci': typeof OAplikaciRoute
  '/odstavky': typeof OdstavkyRoute
  '/pracoviste': typeof PracovisteRoute
  '/premereni-norem': typeof PremereniNoremRoute
  '/produkty': typeof ProduktyRoute
  '/quality-alerty': typeof QualityAlertyRoute
  '/reporty': typeof ReportyRoute
  '/tydenni-data': typeof TydenniDataRoute
  '/uzivatele': typeof UzivateleRoute
  '/zamestnanci': typeof ZamestnanciRoute
  '/zebricek': typeof ZebricekRoute
  '/interaktivni/mapa': typeof InteraktivniMapaRoute
  '/interaktivni/pracoviste-mapa': typeof InteraktivniPracovisteMapaRoute
  '/interaktivni/smena-obsazeni': typeof InteraktivniSmenaObsazeniRoute
  '/interaktivni/smena-vyroba': typeof InteraktivniSmenaVyrobaRoute
  '/interaktivni/tymy': typeof InteraktivniTymyRoute
  '/zamestnanec/$id': typeof ZamestnanecIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interaktivni'
    | '/analyza'
    | '/anomalie'
    | '/denni-data'
    | '/grafy'
    | '/hodnoceni'
    | '/hromadny-prepocet'
    | '/ke-schvaleni'
    | '/moje-vysledky'
    | '/o-aplikaci'
    | '/odstavky'
    | '/pracoviste'
    | '/premereni-norem'
    | '/produkty'
    | '/quality-alerty'
    | '/reporty'
    | '/tydenni-data'
    | '/uzivatele'
    | '/zamestnanci'
    | '/zebricek'
    | '/interaktivni/mapa'
    | '/interaktivni/pracoviste-mapa'
    | '/interaktivni/smena-obsazeni'
    | '/interaktivni/smena-vyroba'
    | '/interaktivni/tymy'
    | '/zamestnanec/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interaktivni'
    | '/analyza'
    | '/anomalie'
    | '/denni-data'
    | '/grafy'
    | '/hodnoceni'
    | '/hromadny-prepocet'
    | '/ke-schvaleni'
    | '/moje-vysledky'
    | '/o-aplikaci'
    | '/odstavky'
    | '/pracoviste'
    | '/premereni-norem'
    | '/produkty'
    | '/quality-alerty'
    | '/reporty'
    | '/tydenni-data'
    | '/uzivatele'
    | '/zamestnanci'
    | '/zebricek'
    | '/interaktivni/mapa'
    | '/interaktivni/pracoviste-mapa'
    | '/interaktivni/smena-obsazeni'
    | '/interaktivni/smena-vyroba'
    | '/interaktivni/tymy'
    | '/zamestnanec/$id'
  id:
    | '__root__'
    | '/'
    | '/interaktivni'
    | '/analyza'
    | '/anomalie'
    | '/denni-data'
    | '/grafy'
    | '/hodnoceni'
    | '/hromadny-prepocet'
    | '/ke-schvaleni'
    | '/moje-vysledky'
    | '/o-aplikaci'
    | '/odstavky'
    | '/pracoviste'
    | '/premereni-norem'
    | '/produkty'
    | '/quality-alerty'
    | '/reporty'
    | '/tydenni-data'
    | '/uzivatele'
    | '/zamestnanci'
    | '/zebricek'
    | '/interaktivni/mapa'
    | '/interaktivni/pracoviste-mapa'
    | '/interaktivni/smena-obsazeni'
    | '/interaktivni/smena-vyroba'
    | '/interaktivni/tymy'
    | '/zamestnanec/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InteraktivniRouteRoute: typeof InteraktivniRouteRouteWithChildren
  AnalyzaRoute: typeof AnalyzaRoute
  AnomalieRoute: typeof AnomalieRoute
  DenniDataRoute: typeof DenniDataRoute
  GrafyRoute: typeof GrafyRoute
  HodnoceniRoute: typeof HodnoceniRoute
  HromadnyPrepocetRoute: typeof HromadnyPrepocetRoute
  KeSchvaleniRoute: typeof KeSchvaleniRoute
  MojeVysledkyRoute: typeof MojeVysledkyRoute
  OAplikaciRoute: typeof OAplikaciRoute
  OdstavkyRoute: typeof OdstavkyRoute
  PracovisteRoute: typeof PracovisteRoute
  PremereniNoremRoute: typeof PremereniNoremRoute
  ProduktyRoute: typeof ProduktyRoute
  QualityAlertyRoute: typeof QualityAlertyRoute
  ReportyRoute: typeof ReportyRoute
  TydenniDataRoute: typeof TydenniDataRoute
  UzivateleRoute: typeof UzivateleRoute
  ZamestnanciRoute: typeof ZamestnanciRoute
  ZebricekRoute: typeof ZebricekRoute
  ZamestnanecIdRoute: typeof ZamestnanecIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyza': {
      id: '/analyza'
      path: '/analyza'
      fullPath: '/analyza'
      preLoaderRoute: typeof AnalyzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalie': {
      id: '/anomalie'
      path: '/anomalie'
      fullPath: '/anomalie'
      preLoaderRoute: typeof AnomalieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denni-data': {
      id: '/denni-data'
      path: '/denni-data'
      fullPath: '/denni-data'
      preLoaderRoute: typeof DenniDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grafy': {
      id: '/grafy'
      path: '/grafy'
      fullPath: '/grafy'
      preLoaderRoute: typeof GrafyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hodnoceni': {
      id: '/hodnoceni'
      path: '/hodnoceni'
      fullPath: '/hodnoceni'
      preLoaderRoute: typeof HodnoceniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hromadny-prepocet': {
      id: '/hromadny-prepocet'
      path: '/hromadny-prepocet'
      fullPath: '/hromadny-prepocet'
      preLoaderRoute: typeof HromadnyPrepocetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interaktivni': {
      id: '/interaktivni'
      path: '/interaktivni'
      fullPath: '/interaktivni'
      preLoaderRoute: typeof InteraktivniRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ke-schvaleni': {
      id: '/ke-schvaleni'
      path: '/ke-schvaleni'
      fullPath: '/ke-schvaleni'
      preLoaderRoute: typeof KeSchvaleniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moje-vysledky': {
      id: '/moje-vysledky'
      path: '/moje-vysledky'
      fullPath: '/moje-vysledky'
      preLoaderRoute: typeof MojeVysledkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-aplikaci': {
      id: '/o-aplikaci'
      path: '/o-aplikaci'
      fullPath: '/o-aplikaci'
      preLoaderRoute: typeof OAplikaciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odstavky': {
      id: '/odstavky'
      path: '/odstavky'
      fullPath: '/odstavky'
      preLoaderRoute: typeof OdstavkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pracoviste': {
      id: '/pracoviste'
      path: '/pracoviste'
      fullPath: '/pracoviste'
      preLoaderRoute: typeof PracovisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premereni-norem': {
      id: '/premereni-norem'
      path: '/premereni-norem'
      fullPath: '/premereni-norem'
      preLoaderRoute: typeof PremereniNoremRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty': {
      id: '/produkty'
      path: '/produkty'
      fullPath: '/produkty'
      preLoaderRoute: typeof ProduktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-alerty': {
      id: '/quality-alerty'
      path: '/quality-alerty'
      fullPath: '/quality-alerty'
      preLoaderRoute: typeof QualityAlertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporty': {
      id: '/reporty'
      path: '/reporty'
      fullPath: '/reporty'
      preLoaderRoute: typeof ReportyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tydenni-data': {
      id: '/tydenni-data'
      path: '/tydenni-data'
      fullPath: '/tydenni-data'
      preLoaderRoute: typeof TydenniDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uzivatele': {
      id: '/uzivatele'
      path: '/uzivatele'
      fullPath: '/uzivatele'
      preLoaderRoute: typeof UzivateleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamestnanci': {
      id: '/zamestnanci'
      path: '/zamestnanci'
      fullPath: '/zamestnanci'
      preLoaderRoute: typeof ZamestnanciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zebricek': {
      id: '/zebricek'
      path: '/zebricek'
      fullPath: '/zebricek'
      preLoaderRoute: typeof ZebricekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interaktivni/mapa': {
      id: '/interaktivni/mapa'
      path: '/mapa'
      fullPath: '/interaktivni/mapa'
      preLoaderRoute: typeof InteraktivniMapaRouteImport
      parentRoute: typeof InteraktivniRouteRoute
    }
    '/interaktivni/pracoviste-mapa': {
      id: '/interaktivni/pracoviste-mapa'
      path: '/pracoviste-mapa'
      fullPath: '/interaktivni/pracoviste-mapa'
      preLoaderRoute: typeof InteraktivniPracovisteMapaRouteImport
      parentRoute: typeof InteraktivniRouteRoute
    }
    '/interaktivni/smena-obsazeni': {
      id: '/interaktivni/smena-obsazeni'
      path: '/smena-obsazeni'
      fullPath: '/interaktivni/smena-obsazeni'
      preLoaderRoute: typeof InteraktivniSmenaObsazeniRouteImport
      parentRoute: typeof InteraktivniRouteRoute
    }
    '/interaktivni/smena-vyroba': {
      id: '/interaktivni/smena-vyroba'
      path: '/smena-vyroba'
      fullPath: '/interaktivni/smena-vyroba'
      preLoaderRoute: typeof InteraktivniSmenaVyrobaRouteImport
      parentRoute: typeof InteraktivniRouteRoute
    }
    '/interaktivni/tymy': {
      id: '/interaktivni/tymy'
      path: '/tymy'
      fullPath: '/interaktivni/tymy'
      preLoaderRoute: typeof InteraktivniTymyRouteImport
      parentRoute: typeof InteraktivniRouteRoute
    }
    '/zamestnanec/$id': {
      id: '/zamestnanec/$id'
      path: '/zamestnanec/$id'
      fullPath: '/zamestnanec/$id'
      preLoaderRoute: typeof ZamestnanecIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InteraktivniRouteRouteChildren {
  InteraktivniMapaRoute: typeof InteraktivniMapaRoute
  InteraktivniPracovisteMapaRoute: typeof InteraktivniPracovisteMapaRoute
  InteraktivniSmenaObsazeniRoute: typeof InteraktivniSmenaObsazeniRoute
  InteraktivniSmenaVyrobaRoute: typeof InteraktivniSmenaVyrobaRoute
  InteraktivniTymyRoute: typeof InteraktivniTymyRoute
}

const InteraktivniRouteRouteChildren: InteraktivniRouteRouteChildren = {
  InteraktivniMapaRoute: InteraktivniMapaRoute,
  InteraktivniPracovisteMapaRoute: InteraktivniPracovisteMapaRoute,
  InteraktivniSmenaObsazeniRoute: InteraktivniSmenaObsazeniRoute,
  InteraktivniSmenaVyrobaRoute: InteraktivniSmenaVyrobaRoute,
  InteraktivniTymyRoute: InteraktivniTymyRoute,
}

const InteraktivniRouteRouteWithChildren =
  InteraktivniRouteRoute._addFileChildren(InteraktivniRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InteraktivniRouteRoute: InteraktivniRouteRouteWithChildren,
  AnalyzaRoute: AnalyzaRoute,
  AnomalieRoute: AnomalieRoute,
  DenniDataRoute: DenniDataRoute,
  GrafyRoute: GrafyRoute,
  HodnoceniRoute: HodnoceniRoute,
  HromadnyPrepocetRoute: HromadnyPrepocetRoute,
  KeSchvaleniRoute: KeSchvaleniRoute,
  MojeVysledkyRoute: MojeVysledkyRoute,
  OAplikaciRoute: OAplikaciRoute,
  OdstavkyRoute: OdstavkyRoute,
  PracovisteRoute: PracovisteRoute,
  PremereniNoremRoute: PremereniNoremRoute,
  ProduktyRoute: ProduktyRoute,
  QualityAlertyRoute: QualityAlertyRoute,
  ReportyRoute: ReportyRoute,
  TydenniDataRoute: TydenniDataRoute,
  UzivateleRoute: UzivateleRoute,
  ZamestnanciRoute: ZamestnanciRoute,
  ZebricekRoute: ZebricekRoute,
  ZamestnanecIdRoute: ZamestnanecIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
