// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession()
    let session = data.session

    // A serverFn must never receive an expired JWT. Supabase normally refreshes
    // in the background, but a tab can sleep or miss the refresh timer. Refresh
    // proactively when the token expires soon, then attach the fresh token.
    if (session?.expires_at && session.expires_at <= Math.floor(Date.now() / 1000) + 60) {
      const refreshed = await supabase.auth.refreshSession()
      session = refreshed.data.session ?? null
    }

    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
